{% set name = "ptvsd" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 3b05c06018fdbce5943c50fb0baac695b5c11326f9e21a5266c854306bda28ab
  patches:                            # [win and py>=38]
    - 0001-python-header-split.patch  # [win and py>=38]

build:
  number: 1
  binary_relocation: False  # [osx]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python
    - pip
    - pytest-runner
    - setuptools
  run:
    - python

test:
  imports:
    - ptvsd

about:
  home: https://github.com/Microsoft/ptvsd/
  license: MIT
  license_file: LICENSE
  summary: 'Python debugger package for use with Visual Studio and Visual Studio Code'

extra:
  recipe-maintainers:
    - int19h
    - karthiknadig
    - dhirschfeld
    - rzillman
