appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: v6cOh2kPREXgB3zdIL+q0KoEOITXGEDQRyOs7slXC23j9E3FfOrgpLf0l/VhQ1rBWTYkByIzKe8QzTBhKBYxQUhbvo83llzTqf8s1Un1KgaACV4UTY9V6DR++5t00k89v1s16BfReWPmqpvhbFOmfc6Hgcu56sXtf/iiT0lS1/+8ILQWknEu8w6ZHG4fhgt7KzXuXJKad5QUV6ADv+zFhcJqaGZJupcnpZEg+JahAm33u8tDjaW1DKuVrglPzfQvoyKOqHhIhN967aW43/ycCY6VclEmIKtSjzo7mruEQL3QJbTwOE08th1+mAKRFL1VmKMalskzDb23onqBsjVvv+RluIig6yQZPVIWPtzeKJySVQuCi7aNd5ghqwWo1bnQRAbot913PR+fz8smeb1txhNth5dBkt2Fg39VRYA5LwL2SuzqLNibDe7jAhj5w7kdET3jCgeLo2lIqm+94ER+NJaqwhmjBlg+QS30NCjWZhSVyz57ZS/8zp/Tr0qC0ipl9aGfCMgRsBHbP5LY1inlMjPOeApzMyO8r7j6zMugZyq1bQv/e0VTrao9YN5OobiyO/cBZ12G1XpV8UZk+D9hj3Tc0zL6fn258rJzWgT/Q0twyb40GZLiABmMo9p7ifleYf/lrd2SwRRFQjcdncwF1RMAEy1OonC3AElrqFcPw90=}
provider:
  win: azure
